### ISSUE TITLE
Can't edit user with .

### ISSUE THREAD

**Issue by CydGoblin** [LCD344/Kirby-userManager-panel-extention#3]
If the username as a dot on it you can't edit it, it says their page doesn't exist

**Comment by LCD344** [comment]
Could you please give some steps to reproduce this? I've been using this in many of my projects where usernames are emails, and they work without a problem (emails have . in them)

**Comment by CydGoblin** [comment]
thanks for the help. This is what I tried today:
- Made a new install of plainkit kirby. It's on a vhost with MAMP
- Installed userManager with kirby CLI
- Created a test user without . in the name, it worked fine
- Created user from userManager. Username is test@test.com and saved
- It redirected to an empty page. Can't load any page in kirby panel. they are all blank.

Did the same with `gulp-connect-php` and got this when creating the user with an email as username
```
Fatal error: Uncaught Exception: The user account could not be found in /kirby2/kirby/core/user.php:24 Stack trace: #0 /kirby2/kirby/core/users.php(26): UserAbstract->__construct('test@startup....') #1 /kirby2/kirby/core/site.php(304): UsersAbstract->__construct() #2 /kirby2/panel/app/src/panel/installer.php(11): SiteAbstract->users() #3 /kirby2/site/plugins/userManager/Panel/Router/filters.php(28): Kirby\Panel\Installer->isCompleted() #4 /kirby2/kirby/vendor/getkirby/toolkit/helpers.php(282): lcd344\Panel\Router\{closure}(Object(Obj)) #5 /kirby2/kirby/vendor/getkirby/toolkit/lib/router.php(189): call(Object(Closure), Array) #6 /kirby2/kirby/vendor/getkirby/toolkit/lib/router.php(239): Router->filterer(Array, Object(Obj)) #7 /kirby2/kirby/core/user.php on line 24
```

Got the same error with mac's build in php server

**Comment by LCD344** [comment]
@Turqueso - Hi, I'm very sorry for not answering before, I didn't get the notification for it.

Quick check shows that users with "non normal" names (illegal characters in kirby) would only work with custom user  folder. Seems that this is a problem with the new version of kirby, where it doesn't like having any file with illegal characters in the accounts folder, even if its not the current logged user.

if you define a custom user folder - 
`c::set("userManager.folder","users");`
for example, this will work only for front end users though.

I will look if I can make changes to this, but I suspect this is a kirby thing, not a userManager Thing
